version: "3.7"
services:
  api:
    build: ./api
    image: postor/high-load-demo-api
    depends_on:
      - redis
    ports:
      - "3009:3000"

  sync:
    build: ./sync
    image: postor/high-load-demo-sync    
    depends_on:
      - redis
      - mongodb

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis:/bitnami/redis/data

  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - mongodb:/bitnami

volumes:
  mongodb:
  redis: