version: "3.7"
services:
  api:
    build: ./api
    image: postor/high-load-demo-api
    deploy:
      mode: global

  sync:
    build: ./sync
    image: postor/high-load-demo-sync
    
    depends_on:
      - db
      - mongodb

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis:/bitnami/redis/data

  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - /path/to/mongodb-persistence:/bitnami